ALTER TABLE exhibitions ADD COLUMN IF NOT EXISTS country_slug VARCHAR(160);
ALTER TABLE exhibitions ADD COLUMN IF NOT EXISTS city_slug VARCHAR(160);
ALTER TABLE exhibitions ADD COLUMN IF NOT EXISTS industry_slug VARCHAR(160);
ALTER TABLE exhibitions ADD COLUMN IF NOT EXISTS starting_price VARCHAR(160);

ALTER TABLE guides ADD COLUMN IF NOT EXISTS related_destination_slug VARCHAR(160);
ALTER TABLE guides ADD COLUMN IF NOT EXISTS related_tour_id VARCHAR(160);